# North-star layer: property-driven workflow synthesis (AGENTS.md charter).
# Appended to the generated RDF by gen_aiida_reharness.py via parts.extend(NORTH_STAR).
# Goal: generate computational workflows on-the-fly from the ontology,
# depending on the TARGET PROPERTY from a hierarchy.

ARH_NS = "https://mpds.io/ontology#"
BASE_NS = "http://www.semanticweb.org/ivan/ontologies/2024/0/ontomat#"
XSD_NS = "http://www.w3.org/2001/XMLSchema#"

NORTH_STAR = [
    "<!-- ============ NORTH-STAR: property-driven workflow synthesis ========= -->",
    '<owl:Class rdf:about="https://mpds.io/ontology#ComputationalWorkflow">',
    "\t<rdfs:subClassOf rdf:resource=\"https://mpds.io/ontology#ComputationalArtefact\"/>",
    "\t<rdfs:comment>A workflow (workchain composition) computing material properties. The subject of on-the-fly generation: the plan names a property; the ontology supplies the workflow that realizes it.</rdfs:comment>",
    "</owl:Class>",
    '<owl:Class rdf:about="https://mpds.io/ontology#WorkChainStep">',
    "\t<rdfs:subClassOf rdf:resource=\"https://mpds.io/ontology#ComputationalArtefact\"/>",
    "\t<rdfs:comment>One AiiDA workchain in a workflow composition.</rdfs:comment>",
    "</owl:Class>",
    # workchain-step individuals
    '<rdf:Description rdf:about="https://mpds.io/ontology#wc_fleur_scf">',
    '\t<rdf:type rdf:resource="https://mpds.io/ontology#WorkChainStep"/>',
    "\t<rdfs:comment>fleur.mpds SCF + geometry optimization (the campaign workhorse).</rdfs:comment>",
    "</rdf:Description>",
    '<rdf:Description rdf:about="https://mpds.io/ontology#wc_fleur_dos">',
    '\t<rdf:type rdf:resource="https://mpds.io/ontology#WorkChainStep"/>',
    "\t<rdfs:comment>fleur.dos_seebeck: DOS + Seebeck from a converged SCF.</rdfs:comment>",
    "</rdf:Description>",
    '<rdf:Description rdf:about="https://mpds.io/ontology#wc_crystal_scf">',
    '\t<rdf:type rdf:resource="https://mpds.io/ontology#WorkChainStep"/>',
    "\t<rdfs:comment>crystal.mpds SCF (Pcrystal).</rdfs:comment>",
    "</rdf:Description>",
    '<rdf:Description rdf:about="https://mpds.io/ontology#wc_crystal_seebeck">',
    '\t<rdf:type rdf:resource="https://mpds.io/ontology#WorkChainStep"/>',
    "\t<rdfs:comment>crystal.mpds_seebeck.</rdfs:comment>",
    "</rdf:Description>",
    '<rdf:Description rdf:about="https://mpds.io/ontology#wc_phonon">',
    '\t<rdf:type rdf:resource="https://mpds.io/ontology#WorkChainStep"/>',
    "\t<rdfs:comment>Phonon stage: FLEUR phonon workflow / CRYSTAL FREQCALC (+PREOPTGEOM INSIDE the FREQCALC block, never a sibling keyword).</rdfs:comment>",
    "</rdf:Description>",
    # properties linking plan -> property -> workflow -> steps
    '<owl:ObjectProperty rdf:about="https://mpds.io/ontology#hasTargetProperty">',
    '\t<rdfs:domain rdf:resource="https://mpds.io/ontology#CampaignPlan"/>',
    '\t<rdfs:range rdf:resource="http://www.semanticweb.org/ivan/ontologies/2024/0/ontomat#Property"/>',
    "\t<rdfs:comment>The material property the campaign computes — the hierarchy entry the plan is generated FROM.</rdfs:comment>",
    "</owl:ObjectProperty>",
    '<owl:ObjectProperty rdf:about="https://mpds.io/ontology#realizedBy">',
    '\t<rdfs:domain rdf:resource="http://www.semanticweb.org/ivan/ontologies/2024/0/ontomat#Property"/>',
    '\t<rdfs:range rdf:resource="https://mpds.io/ontology#ComputationalWorkflow"/>',
    "\t<rdfs:comment>A base Property individual is realized by this workflow (asserted additively on base individuals).</rdfs:comment>",
    "</owl:ObjectProperty>",
    '<owl:ObjectProperty rdf:about="https://mpds.io/ontology#hasStep">',
    '\t<rdfs:domain rdf:resource="https://mpds.io/ontology#ComputationalWorkflow"/>',
    '\t<rdfs:range rdf:resource="https://mpds.io/ontology#WorkChainStep"/>',
    "\t<rdfs:comment>Composition: a workflow runs these workchain steps.</rdfs:comment>",
    "</owl:ObjectProperty>",
    # workflow subclasses + template individuals (the generation seeds)
    '<owl:Class rdf:about="https://mpds.io/ontology#SeebeckWorkflow">',
    '\t<rdfs:subClassOf rdf:resource="https://mpds.io/ontology#ComputationalWorkflow"/>',
    "\t<rdfs:comment>Seebeck coefficient: SCF convergence then DOS/Seebeck stage.</rdfs:comment>",
    "</owl:Class>",
    '<owl:Class rdf:about="https://mpds.io/ontology#PhononWorkflow">',
    '\t<rdfs:subClassOf rdf:resource="https://mpds.io/ontology#ComputationalWorkflow"/>',
    "\t<rdfs:comment>Phonon spectrum; imaginary modes route back to geometry optimization (pitfalls 25/27).</rdfs:comment>",
    "</owl:Class>",
    '<rdf:Description rdf:about="https://mpds.io/ontology#wf_fleur_seebeck">',
    '\t<rdf:type rdf:resource="https://mpds.io/ontology#SeebeckWorkflow"/>',
    '\t<hasStep rdf:resource="https://mpds.io/ontology#wc_fleur_scf"/>',
    '\t<hasStep rdf:resource="https://mpds.io/ontology#wc_fleur_dos"/>',
    "\t<rdfs:comment>FLEUR route: fleur.mpds SCF then fleur.dos_seebeck.</rdfs:comment>",
    "</rdf:Description>",
    '<rdf:Description rdf:about="https://mpds.io/ontology#wf_crystal_seebeck">',
    '\t<rdf:type rdf:resource="https://mpds.io/ontology#SeebeckWorkflow"/>',
    '\t<hasStep rdf:resource="https://mpds.io/ontology#wc_crystal_scf"/>',
    '\t<hasStep rdf:resource="https://mpds.io/ontology#wc_crystal_seebeck"/>',
    "\t<rdfs:comment>CRYSTAL route: crystal.mpds SCF then crystal.mpds_seebeck.</rdfs:comment>",
    "</rdf:Description>",
    '<rdf:Description rdf:about="https://mpds.io/ontology#wf_crystal_phonon">',
    '\t<rdf:type rdf:resource="https://mpds.io/ontology#PhononWorkflow"/>',
    '\t<hasStep rdf:resource="https://mpds.io/ontology#wc_crystal_scf"/>',
    '\t<hasStep rdf:resource="https://mpds.io/ontology#wc_phonon"/>',
    "\t<rdfs:comment>CRYSTAL FREQCALC with PREOPTGEOM inside the block.</rdfs:comment>",
    "</rdf:Description>",
    # a plan that names its target property (the generation entry point).
    # equivalentClass, not bare subClassOf: subClassOf is only a NECESSARY
    # condition — instance classification needs the sufficient direction.
    '<owl:Class rdf:about="https://mpds.io/ontology#PropertyTargetedPlan">',
    '\t<rdfs:subClassOf rdf:resource="https://mpds.io/ontology#CampaignPlan"/>',
    "\t<rdfs:comment>A plan generated FROM a property-hierarchy entry (hasTargetProperty some base Property).</rdfs:comment>",
    '\t<owl:equivalentClass>',
    '\t\t<owl:Class>',
    '\t\t\t<owl:intersectionOf rdf:parseType="Collection">',
    '\t\t\t\t<owl:Class rdf:about="https://mpds.io/ontology#CampaignPlan"/>',
    '\t\t\t\t<owl:Restriction>',
    '\t\t\t\t\t<owl:onProperty rdf:resource="https://mpds.io/ontology#hasTargetProperty"/>',
    '\t\t\t\t\t<owl:someValuesFrom rdf:resource="http://www.semanticweb.org/ivan/ontologies/2024/0/ontomat#Property"/>',
    '\t\t\t\t</owl:Restriction>',
    '\t\t\t</owl:intersectionOf>',
    '\t\t</owl:Class>',
    '\t</owl:equivalentClass>',
    "</owl:Class>",
]